#User Sign Up
POST http://localhost:8080/api/user/sign-up
Content-Type: application/json

{
    "firstName": "Fawaz",
    "lastName": "Odesanya",
    "telephone": "09059595959",
    "email": "fawaz@test.com"
}

###
GET http://localhost:8080/api/entry/winners/list

###
GET http://localhost:8080/